# Generated by Django 4.2.4 on 2023-08-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=80)),
                ('pronunciation', models.TextField()),
                ('translation', models.CharField(max_length=80)),
            ],
        ),
    ]
